	languageCode = "en-us"
	title = "Tardigrade | Decentralized Cloud Object Storage"

	[permalinks]
		partner = "/partner/"
		privacy-policy = "/privacy-policy/"
		support="/support/"
		terms-of-use = "/terms-of-use/"
		terms-of-service = "/terms-of-service/"
		acceptable-use-policy="/acceptable-use-policy/"
		code-of-conduct = "/code-of-conduct/"
		cookie-policy="/cookie-policy/"
		notice-takedown-policy="/notice-takedown-policy/"
		support-policy="/support-policy/"
		community="/community/"
		press-kit="/press-kit/"
		tech-partner = "/tech-partner/"
		partner-form="/partner-form/"
		partner-thank-you="/partner-thank-you/"
		universal-login="/login/"
		universal-signup="/signup/"
		satellites-verify="/verify/"
		unsubscribed-newsletters="/unsubscribed-newsletters/"
		unsubscribed-notifications="/unsubscribed-notifications/"
		covid="/covid/"
		connectors="/connectors/"
		how-it-works="/how-it-works/"
		404 = "/404/"
		filezilla="/connectors/filezilla"
		partner-fork="/partners/"
		about-us="/about-us/"
		duplicati="/connectors/duplicati"
		why="/whats-a-tardigrade/"
